apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wordsform","name":"fastapi-words"},"name":"fastapi-service","namespace":"wordsform"},"spec":{"ports":[{"name":"fastapi-service","nodePort":31000,"port":80,"targetPort":8900}],"selector":{"app":"wordsform","name":"fastapi-words"},"type":"NodePort"}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  labels:
    app: wordsform
    name: fastapi-words
  name: fastapi-service
  namespace: wordsform
  resourceVersion: "1374"
  uid: aecf937c-36b5-4bc7-aed6-0dd4833983ff
spec:
  clusterIP: 10.101.68.241
  clusterIPs:
  - 10.101.68.241
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: fastapi-service
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 8900
  selector:
    app: wordsform
    name: fastapi-words
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
