apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wordsform"},"name":"fastapi-words","namespace":"wordsform"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordsform","name":"fastapi-words"}},"template":{"metadata":{"labels":{"app":"wordsform","name":"fastapi-words"},"name":"fastapi-words"},"spec":{"containers":[{"image":"larturi/wordsform-fastapi:latest","name":"fastapi-words","ports":[{"containerPort":8900,"name":"fastapi-words"}]}]}}}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  generation: 1
  labels:
    app: wordsform
  name: fastapi-words
  namespace: wordsform
  resourceVersion: "1419"
  uid: f6b5a07a-208b-4f71-a33b-bd700bd16167
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordsform
      name: fastapi-words
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordsform
        name: fastapi-words
      name: fastapi-words
    spec:
      containers:
      - image: larturi/wordsform-fastapi:latest
        imagePullPolicy: Always
        name: fastapi-words
        ports:
        - containerPort: 8900
          name: fastapi-words
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-03T22:30:42Z"
    lastUpdateTime: "2023-06-03T22:30:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-03T22:30:35Z"
    lastUpdateTime: "2023-06-03T22:30:42Z"
    message: ReplicaSet "fastapi-words-7bd9cd5ccd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
