apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wordsform"},"name":"next-client-app","namespace":"wordsform"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordsform","name":"next-client-app"}},"template":{"metadata":{"labels":{"app":"wordsform","name":"next-client-app"},"name":"next-client-app"},"spec":{"containers":[{"env":[{"name":"NEXT_PUBLIC_URL_SERVICE_WORD_FAMILY","value":"http://localhost:31000"}],"image":"larturi/wordsform-next-app:latest","name":"next-client-app","ports":[{"containerPort":3000,"name":"next-client-app"}]}]}}}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  generation: 1
  labels:
    app: wordsform
  name: next-client-app
  namespace: wordsform
  resourceVersion: "1399"
  uid: cc6fc2e6-f480-44fa-a788-1e6ee893e769
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordsform
      name: next-client-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordsform
        name: next-client-app
      name: next-client-app
    spec:
      containers:
      - env:
        - name: NEXT_PUBLIC_URL_SERVICE_WORD_FAMILY
          value: http://localhost:31000
        image: larturi/wordsform-next-app:latest
        imagePullPolicy: Always
        name: next-client-app
        ports:
        - containerPort: 3000
          name: next-client-app
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-03T22:30:39Z"
    lastUpdateTime: "2023-06-03T22:30:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-03T22:30:35Z"
    lastUpdateTime: "2023-06-03T22:30:39Z"
    message: ReplicaSet "next-client-app-5d6c45c895" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
