apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wordsform","name":"next-client-app"},"name":"next-client-app","namespace":"wordsform"},"spec":{"ports":[{"name":"next-client-app","nodePort":32000,"port":80,"targetPort":3000}],"selector":{"app":"wordsform","name":"next-client-app"},"type":"NodePort"}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  labels:
    app: wordsform
    name: next-client-app
  name: next-client-app
  namespace: wordsform
  resourceVersion: "1383"
  uid: 11e71055-7103-4212-91f0-7ca73b224007
spec:
  clusterIP: 10.101.2.204
  clusterIPs:
  - 10.101.2.204
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: next-client-app
    nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: wordsform
    name: next-client-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
