apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"wordsform","name":"php-translate"},"name":"php-translate","namespace":"wordsform"},"spec":{"ports":[{"name":"php-translate","nodePort":31001,"port":80,"targetPort":80}],"selector":{"app":"wordsform","name":"php-translate"},"type":"NodePort"}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  labels:
    app: wordsform
    name: php-translate
  name: php-translate
  namespace: wordsform
  resourceVersion: "1378"
  uid: 6a133e7f-8b99-4a7f-99ee-31f45ec6d316
spec:
  clusterIP: 10.101.44.156
  clusterIPs:
  - 10.101.44.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: php-translate
    nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordsform
    name: php-translate
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
