apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wordsform"},"name":"php-translate","namespace":"wordsform"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordsform","name":"php-translate"}},"template":{"metadata":{"labels":{"app":"wordsform","name":"php-translate"},"name":"php-translate"},"spec":{"containers":[{"image":"larturi/wordsform-php-translate:latest","name":"php-translate","ports":[{"containerPort":80,"name":"php-translate"}]}]}}}}
  creationTimestamp: "2023-06-03T22:30:35Z"
  generation: 1
  labels:
    app: wordsform
  name: php-translate
  namespace: wordsform
  resourceVersion: "1409"
  uid: 9731924a-e763-4dda-a601-01688a3839f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordsform
      name: php-translate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordsform
        name: php-translate
      name: php-translate
    spec:
      containers:
      - image: larturi/wordsform-php-translate:latest
        imagePullPolicy: Always
        name: php-translate
        ports:
        - containerPort: 80
          name: php-translate
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-03T22:30:40Z"
    lastUpdateTime: "2023-06-03T22:30:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-03T22:30:35Z"
    lastUpdateTime: "2023-06-03T22:30:40Z"
    message: ReplicaSet "php-translate-56c88b67db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
