apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-words
  labels:
    app: wordsform
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fastapi-words
      app: wordsform
  template:
    metadata:
      name: fastapi-words
      labels:
        name: fastapi-words
        app: wordsform
    spec:
      containers:
      - name: fastapi-words
        image: larturi/wordsform-fastapi:latest
        ports:
        - containerPort: 8900
          name: fastapi-words

