apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    name: fastapi-words
    app: wordsform
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8900
    nodePort: 31000
    name: "fastapi-service"
  selector:
    name: fastapi-words
    app: wordsform
